### ISSUE TITLE
Impossible to install 

### ISSUE THREAD

**Issue by aborruso** [beatfreaker/text-meme-cli#8]
Hi,
I have these errors.

I'm using debian buster.

Thank you

```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
/home/aborruso/n/bin/text-meme -> /home/aborruso/n/lib/node_modules/text-meme-cli/cli.js

> canvas@1.6.13 install /home/aborruso/n/lib/node_modules/text-meme-cli/node_modules/canvas
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:290:12)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/home/aborruso/n/bin/node" "/home/aborruso/n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aborruso/n/lib/node_modules/text-meme-cli/node_modules/canvas
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aborruso/.npm/_logs/2019-06-23T09_15_10_978Z-debug.log
```

**Comment by aborruso** [comment]
It's necessary to use python2 :(
